USE RAM_UNIVER;

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;


SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%компьютер%';


/*SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
FROM AUDITORIUM,AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;*/


SELECT T1.AUDITORIUM, T2.AUDITORIUM_TYPENAME 
FROM AUDITORIUM AS T1,AUDITORIUM_TYPE AS T2
WHERE T1.AUDITORIUM_TYPE = T2.AUDITORIUM_TYPE;


SELECT FACULTY.FACULTY[Факультет], STUDENT.NAME[Студент], PROGRESS.SUBJECT[Предмет], PROGRESS.NOTE[Оценка], PULPIT.PULPIT[Кафедра], PROFESSION.PROFESSION_NAME[Специальность],
     CASE PROGRESS.NOTE
	     WHEN 6 THEN 'шесть'
		 WHEN 7 THEN 'семь'
		 WHEN 8 THEN 'восемь'
		 ELSE ''
     END Оценка
FROM FACULTY, STUDENT, PROGRESS, PULPIT, PROFESSION
WHERE PROGRESS.NOTE BETWEEN 6 AND 8;


SELECT FACULTY.FACULTY[Факультет], STUDENT.NAME[Студент], PROGRESS.SUBJECT[Предмет], PROGRESS.NOTE[Оценка], PULPIT.PULPIT[Кафедра], PROFESSION.PROFESSION_NAME[Специальность],
     CASE PROGRESS.NOTE
	     WHEN 6 THEN 'шесть'
		 WHEN 7 THEN 'семь'
		 WHEN 8 THEN 'восемь'
		 ELSE ''
     END Оценка
FROM FACULTY, STUDENT, PROGRESS, PULPIT, PROFESSION
WHERE PROGRESS.NOTE BETWEEN 6 AND 8
ORDER BY
(
   CASE
       WHEN PROGRESS.NOTE = 8 THEN 1
	   WHEN PROGRESS.NOTE = 7 THEN 2
	   WHEN PROGRESS.NOTE = 6 THEN 3
	END
);


SELECT ISNULL(PULPIT.PULPIT_NAME, '***')[Кафедра], TEACHER.TEACHER_NAME[Преподаватель] 
FROM PULPIT LEFT OUTER JOIN TEACHER
ON PULPIT.PULPIT = TEACHER.PULPIT;


/*Task7*/
SELECT TEACHER.TEACHER_NAME[Преподаватель], ISNULL(PULPIT.PULPIT_NAME, '***')[Кафедра]
FROM TEACHER LEFT OUTER JOIN PULPIT
ON PULPIT.PULPIT = TEACHER.PULPIT;


SELECT ISNULL(PULPIT.PULPIT_NAME, '***')[Кафедра], TEACHER.TEACHER_NAME[Преподаватель]
FROM PULPIT RIGHT OUTER JOIN TEACHER
ON PULPIT.PULPIT = TEACHER.PULPIT;


--Task9
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM CROSS JOIN AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;








--Task8
/*CREATE TABLE TABLE1
(
    ID INT IDENTITY(1,1),
    TEXTBOX CHAR(20)
);

CREATE TABLE TABLE2
(
    ID INT IDENTITY(1,1),
    TEXTBOX CHAR(20)
);

INSERT INTO TABLE1(TEXTBOX) VALUES ('LEFT1');
INSERT INTO TABLE1(TEXTBOX) VALUES ('LEFT2');
INSERT INTO TABLE1(TEXTBOX) VALUES ('LEFT3');

INSERT INTO TABLE2(TEXTBOX) VALUES ('RIGHT1');
INSERT INTO TABLE2(TEXTBOX) VALUES ('RIGHT2');
INSERT INTO TABLE2(TEXTBOX) VALUES ('RIGHT3');*/

/*SELECT *
FROM TABLE1 FULL OUTER JOIN TABLE2
ON TABLE1.TEXTBOX = TABLE2.TEXTBOX;

SELECT *
FROM 
    (SELECT *
     FROM TABLE1 LEFT OUTER JOIN TABLE2
     ON TABLE1.TEXTBOX = TABLE2.TEXTBOX),
	 (SELECT *
     FROM TABLE1 RIGHT OUTER JOIN TABLE2
     ON TABLE1.TEXTBOX = TABLE2.TEXTBOX);*/