USE RAM_UNIVER;

--Task1
SELECT DISTINCT PULPIT.PULPIT_NAME, FACULTY.FACULTY, PROFESSION.PROFESSION_NAME
FROM PULPIT, FACULTY, PROFESSION
WHERE PULPIT.FACULTY = FACULTY.FACULTY AND FACULTY.FACULTY = PROFESSION.FACULTY
AND PROFESSION.PROFESSION_NAME IN
                                 (SELECT PROFESSION_NAME
								  FROM PROFESSION
								  WHERE (PROFESSION_NAME LIKE '%технология%' OR PROFESSION_NAME LIKE '%технологии%'));

--Task
SELECT DISTINCT PULPIT.PULPIT_NAME, FACULTY.FACULTY, PROFESSION.PROFESSION_NAME
FROM FACULTY INNER JOIN PROFESSION
ON FACULTY.FACULTY = PROFESSION.FACULTY
INNER JOIN PULPIT
ON PULPIT.FACULTY = FACULTY.FACULTY
WHERE (PROFESSION_NAME LIKE '%технология%' OR PROFESSION_NAME LIKE '%технологии%');



--Task
SELECT AUDITORIUM, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
FROM AUDITORIUM AS A
WHERE AUDITORIUM_CAPACITY = (SELECT TOP(1) AUDITORIUM_CAPACITY 
                             FROM AUDITORIUM AS B 
							 WHERE A.AUDITORIUM_TYPE = B.AUDITORIUM_TYPE 
							 ORDER BY AUDITORIUM_CAPACITY DESC);


--Task5
SELECT FACULTY
FROM FACULTY
WHERE NOT EXISTS(SELECT * FROM PULPIT WHERE FACULTY.FACULTY = PULPIT.FACULTY);


--Task6
SELECT TOP(1) 
(SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT = 'ОАиП')[ОАиП],
(SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT = 'КГ')[КГ],
(SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT = 'СУБД')[СУБД]
FROM PROGRESS;


--Task8
SELECT * FROM PULPIT WHERE FACULTY = ANY (SELECT FACULTY FROM PROFESSION WHERE FACULTY = 'ИЭФ');

--Task7
SELECT * FROM AUDITORIUM WHERE AUDITORIUM_CAPACITY > ALL (SELECT AUDITORIUM_CAPACITY FROM AUDITORIUM WHERE AUDITORIUM_CAPACITY = 60);

--Task10
SELECT COUNT(NAME)[PEOPLE], BDAY FROM STUDENT GROUP BY BDAY HAVING COUNT(BDAY)>1;