USE RAM_UNIVER;

SELECT * FROM FACULTY;

SELECT  TEACHER, PULPIT FROM TEACHER;

SELECT TEACHER_NAME FROM TEACHER WHERE PULPIT = 'ИСиТ';

SELECT TEACHER_NAME FROM TEACHER WHERE PULPIT = 'ИСиТ' OR PULPIT = 'ПОиСОИ';

SELECT TEACHER_NAME FROM TEACHER WHERE GENDER = 'ж' AND PULPIT = 'ИСиТ';

SELECT TEACHER_NAME[Имя_преподавателя] FROM TEACHER WHERE GENDER != 'ж' AND PULPIT = 'ИСиТ';

SELECT DISTINCT PULPIT FROM TEACHER;

SELECT AUDITORIUM, AUDITORIUM_CAPACITY FROM AUDITORIUM ORDER BY AUDITORIUM_CAPACITY;

SELECT DISTINCT TOP(2) AUDITORIUM_TYPE, AUDITORIUM_CAPACITY FROM AUDITORIUM ORDER BY AUDITORIUM_CAPACITY DESC;

SELECT DISTINCT SUBJECT, NOTE FROM PROGRESS WHERE NOTE BETWEEN 8 AND 10;

SELECT DISTINCT SUBJECT, PULPIT FROM SUBJECT WHERE PULPIT IN ('ЛЗиДВ', 'ПОиСОИ', 'ОВ');

SELECT PROFESSION_NAME[Наименование_специальности], QUALIFICATION[Квалификация] FROM PROFESSION WHERE QUALIFICATION LIKE '%химик%';


/*CREATE TABLE #MYTABLE1
(
      IDSTUDENT   integer identity(1000,1),
      IDGroop   integer,        
      NAME   nvarchar(100), 
      BDAY   date,
      STAMP  timestamp,
      INFO     xml,
      FOTO     varbinary
);*/

SELECT * INTO #MYTABLE0 FROM PULPIT;

SELECT * FROM #MYTABLE0;